---
application:
  name: "adventure-lab-browser"
  project: "adventure-lab-browser"
  organization: "QoveryCommunity"
routers:
- name: "main-adventure-lab-browser"
  routes:
  - application_name: "adventure-lab-browser"
    paths:
    - "/*"
